@api = http://localhost:5000/api
@cmcApi = https://pro-api.coinmarketcap.com/v1

### Get cryptos
GET {{cmcApi}}/cryptocurrency/listings/latest?limit=200&sort=market_cap_strict
Accept: application/json
X-CMC_PRO_API_KEY: d5bd8462-ee1a-4816-9f02-c9cac813cca5
Accept-Encoding: deflate, gzip

### Get global metrics
GET pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest
Accept: application/json
X-CMC_PRO_API_KEY: d5bd8462-ee1a-4816-9f02-c9cac813cca5
Accept-Encoding: deflate, gzip

### Get cryptos finpoq
GET {{api}}/cryptocurrencies?limit=4

### Update cryptos finpoq
GET {{api}}/cryptocurrencies/update

### Fetch cryptos CMC
GET {{api}}/cryptocurrencies/fetch

