FROM node:lts-alpine

WORKDIR /usr/src/app

COPY ./frontend/package.json ./frontend/tsconfig.json ./frontend/yarn.lock /usr/src/app/frontend/

WORKDIR /usr/src/app/frontend

RUN npm install

COPY ./frontend/ ./
COPY ./core/ /usr/src/app/core/

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "serve" ]

