version: "3"
services:
  frontend:
    image: mauvies/finpoq_frontend:latest
    ports:
      - "3000:3000"
    networks:
      - finpo-network
    env_file:
      - ./frontend/.env.prod

  api:
    image: mauvies/finpoq_api:latest
    ports:
      - "5000:5000"
    networks:
      - finpo-network
    env_file:
      - ./api/.env.prod


networks:
  finpo-network:
    driver: bridge
