version: "3"
services:
  frontend:
    image: mauvies/finpoq_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - caddy-data:/data
    - caddy-config:/config
    networks:
      - finpo-network

  api:
    image: mauvies/finpoq_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - finpo-network
    env_file:
      - ./api/.env.prod

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 30


networks:
  finpo-network:
    driver: bridge

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local
