@api = http://localhost:5000

### Register user
POST {{api}}/auth/register
Content-Type: application/json

{
    "name": "maur",
    "email": "mauricio@gmail.com",
    "password": "12345"
}

### Login user
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "mauricio@gmail.com",
    "password": "12345"
}
