@api = http://localhost:5000/api

### Portfolio
GET {{api}}/portfolio
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmI2ZjQ3ZGQ0NDA5ZDAwOGE4NjcxYzYiLCJlbWFpbCI6Im1hdXJpY2lvQGdtYWlsLmNvbSIsImlhdCI6MTY1NjE1NzMyMSwiZXhwIjoxNjU2MzMwMTIxfQ.7RhRNjCt3bZoZvIJeG-HTkrYefuCfJ7dfyny29effOo

### Add transaction
POST {{api}}/portfolio/cryptocurrency
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmI2ZjQ3ZGQ0NDA5ZDAwOGE4NjcxYzYiLCJlbWFpbCI6Im1hdXJpY2lvQGdtYWlsLmNvbSIsImlhdCI6MTY1NjE1NzMyMSwiZXhwIjoxNjU2MzMwMTIxfQ.7RhRNjCt3bZoZvIJeG-HTkrYefuCfJ7dfyny29effOo

{
	"symbol": "BTC",
	"amount": 5,
	"price": 18,
	"time": "2021/08/23",
  "type": "buy"
}


### Remove transaction
POST {{api}}/portfolio/cryptocurrency/remove-transaction
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2Y2NTE5NGU3YjhiNmFmNjQyZTczZSIsIm5hbWUiOiJtYXUiLCJpYXQiOjE2MzE1NDQ2MTIsImV4cCI6MTYzMTcxNzQxMn0.1zlR4QOfxwtCfGCh33JyuDgreag8AfT24_jwkGl-hNM

{
	"assetId": "613f65364e7b8b6af642e745",
	"transactionId": "613f685b08244a6c5f22759f"
}

### Remove crypto
DELETE {{api}}/portfolio/cryptocurrency/613f9cc7a63682758c163938
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2Y2NTE5NGU3YjhiNmFmNjQyZTczZSIsIm5hbWUiOiJtYXUiLCJpYXQiOjE2MzE1NDQ2MTIsImV4cCI6MTYzMTcxNzQxMn0.1zlR4QOfxwtCfGCh33JyuDgreag8AfT24_jwkGl-hNM
