FROM node:lts-alpine

WORKDIR /usr/src/app

COPY ./api/package.json ./api/tsconfig.json /usr/src/app/api/

WORKDIR /usr/src/app/api

RUN npm install

COPY ./api ./
COPY ./core/ /usr/src/app/core/

RUN npm run build

EXPOSE 5000

CMD [ "node", "dist/index.js" ]

