name: Build image and push to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: ./api/Dockerfile.prod
          push: true
          tags: mauvies/finpoq_api:latest

      - name: Build and push frontend docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: ./frontend/Dockerfile.prod
          push: true
          tags: mauvies/finpoq_frontend:latest
